let Clubs = ["notused", "notused",
"cardImages/2OfClubs.png",
"cardImages/2OfClubs.png",
"cardImages/3OfClubs.png",
"cardImages/4OfClubs.png",
"cardImages/5OfClubs.png",
"cardImages/6OfClubs.png",
"cardImages/7OfClubs.png",
"cardImages/8OfClubs.png",
"cardImages/9OfClubs.png",
"cardImages/10OfClubs.png",
"cardImages/jackOfClubs.png",
"cardImages/queenOfClubs.png",
"cardImages/kingOfClubs.png",
"cardImages/aceOfClubs.png"]

let Diamonds = ["notused", "notused",
"cardImages/2OfDiamonds.png",
"cardImages/2OfDiamonds.png",
"cardImages/3OfDiamonds.png",
"cardImages/4OfDiamonds.png",
"cardImages/5OfDiamonds.png",
"cardImages/6OfDiamonds.png",
"cardImages/7OfDiamonds.png",
"cardImages/8OfDiamonds.png",
"cardImages/9OfDiamonds.png",
"cardImages/10OfDiamonds.png",
"cardImages/jackOfDiamonds.png",
"cardImages/queenOfDiamonds.png",
"cardImages/kingOfDiamonds.png",
"cardImages/aceOfDiamonds.png"]

let Hearts = ["notused", "notused",
"cardImages/2OfHearts.png",
"cardImages/3OfHearts.png",
"cardImages/4OfHearts.png",
"cardImages/5OfHearts.png",
"cardImages/6OfHearts.png",
"cardImages/7OfHearts.png",
"cardImages/8OfHearts.png",
"cardImages/9OfHearts.png",
"cardImages/10OfHearts.png",
"cardImages/jackOfHearts.png",
"cardImages/queenOfHearts.png",
"cardImages/kingOfHearts.png",
"cardImages/aceOfHearts.png"]

let Spades = ["notused", "notused",
"cardImages/2OfSpades.png",
"cardImages/3OfSpades.png",
"cardImages/4OfSpades.png",
"cardImages/5OfSpades.png",
"cardImages/6OfSpades.png",
"cardImages/7OfSpades.png",
"cardImages/8OfSpades.png",
"cardImages/9OfSpades.png",
"cardImages/10OfSpades.png",
"cardImages/jackOfSpades.png",
"cardImages/queenOfSpades.png",
"cardImages/kingOfSpades.png",
"cardImages/aceOfSpades.png"]